### ISSUE TITLE
Logcat formatting in HTML report.

### ISSUE THREAD

**Issue by navstyachka** [gojuno/composer#34]
@artem-zinnatullin Currently I have created 4 CSS classes, check if smth is missing, screenshot is attached (if you don't like the colors I've used, just give me a screenshot with console of your taste and I will apply its colors). 

```CSS
.log__info {
  color: $green;
}

.log__debug {
  color: $electric;
}

.log__error {
  color: $red;
}

.log__warn {
  color: $yellow;
}
```
Also, there can be a problem with spaces — no matter how many spaces you add one by one, in browser thay will be trimmed into one. It can be fixed with using `&nbsp;` symbol but that can also be a problem as leads ti nowrap line.

![screenshot 2017-05-30 19 18 10](https://cloud.githubusercontent.com/assets/1816011/26593449/c12d58aa-456c-11e7-8bd1-9bd145ffae92.png)
